pub const DEFAULT_LOG_RING_BUFFER_SIZE: usize = 2;
pub const DEFAULT_TICK_INTERVAL_MSECS: u64 = 250;
pub const DEFAULT_SCREEN_MARGIN: u16 = 0;
pub const MAX_RETAINED_LOG_LINES: usize= 10;
pub const MINIMUM_SERVER_WAIT_SECS: u64 = 15;